name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Bump version
      uses: remorses/bump-version@v3
      with:
        version_file: VERSION
    - name: Publish
      uses: remorses/pypi@v2
      with:
        username: ${{ secrets.pypi_username }}
        password: ${{ secrets.pypi_password }}


    
    
    
    
    
    
    
    
    
    
    
